# Generated by Django 6.0.1 on 2026-02-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foreign_lang_nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(default='Sem descrição')),
                ('foreign_lang_descricao', models.TextField(default='No description')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo_de_prato', models.CharField(choices=[('ENTRADAS/STARTERS', 'EN/ST'), ("ESPECIALIDADES DO CHEFE/CHEF'S SPECIALITIES", 'EC/CS'), ('SOBREMESAS/DESSERTS', 'SM/DS')], max_length=50)),
            ],
        ),
    ]
