# Generated by Django 6.0.1 on 2026-02-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratos',
            name='tipo_de_prato',
            field=models.CharField(choices=[('ENTRADAS/STARTERS', 'ENTRADAS/STARTERS'), ("ESPECIALIDADES DO CHEFE/CHEF'S SPECIALITIES", "ESPECIALIDADES DO CHEFE/CHEF'S SPECIALITIES"), ('SOBREMESAS/DESSERTS', 'SOBREMESAS/DESSERTS')], max_length=50),
        ),
    ]
