# Generated by Django 6.0.1 on 2026-02-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_pratos_tipo_de_prato'),
    ]

    operations = [
        migrations.AddField(
            model_name='pratos',
            name='imagem',
            field=models.ImageField(default='', upload_to='imagem/pratos'),
            preserve_default=False,
        ),
    ]
