# Generated by Django 6.0.1 on 2026-02-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_pratos_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratos',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
