# Generated by Django 6.0.1 on 2026-02-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_pratos_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratos',
            name='tipo_de_prato',
            field=models.CharField(choices=[('ENTRADAS/STARTERS', 'ENTRADAS/STARTERS'), ('MASSA E OVOS/PASTA & EGGS', 'MASSA E OVOS/PASTA & EGGS'), ('SALADAS/SALADS', 'SALADAS/SALADS'), ("ESPECIALIDADES DO CHEFE/CHEF'S SPECIALITIES", "ESPECIALIDADES DO CHEFE/CHEF'S SPECIALITIES"), ('SOBREMESAS/DESSERTS', 'SOBREMESAS/DESSERTS')], max_length=50),
        ),
    ]
