# Generated by Django 6.0.1 on 2026-01-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='telefone',
            field=models.IntegerField(default=None, max_length=9),
        ),
    ]
