# Generated by Django 6.0.1 on 2026-01-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='telefone',
            field=models.CharField(default=None, max_length=9),
        ),
    ]
