# Generated by Django 6.0.1 on 2026-01-23 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
