# Generated by Django 5.2.7 on 2025-10-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(default='Sem descrição')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
    ]
