# Generated by Django 5.2.7 on 2025-11-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(default='Sem descrição')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
    ]
