# Generated by Django 5.2.7 on 2025-11-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicia', '0002_bebidas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.IntegerField()),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('num_de_pessoas', models.IntegerField(verbose_name='Nº de pessoas')),
                ('observacoes', models.TextField()),
            ],
        ),
    ]
