# Generated by Django 5.2.7 on 2025-11-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicia', '0003_reservar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebidas',
            name='preco_por_taca',
            field=models.BooleanField(default=False),
        ),
    ]
