# Generated by Django 5.2.7 on 2025-11-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicia', '0005_alter_bebidas_preco_por_taca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebidas',
            name='preco_por_taca',
            field=models.BooleanField(default=False, verbose_name='Preço por taça/copo'),
        ),
    ]
